### ISSUE TITLE
code looks for kernel32.dll on linux

### ISSUE THREAD

**Issue by blushingpenguin** [DrJohnMelville/Pdf#38]
using the example in the documentation (with ReadFromFile corrected to ReadFromFileAsync):

```c#
using Melville.Pdf.Model;
using Melville.Pdf.SkiaSharp; // Need to reference project Melville.Pdf.SkiaSharp

namespace Test;

class Program
{
    public static async Task Main()
    {
        var document = await new PdfReader().ReadFromFileAsync("w_5740.pdf");
        // using var output = new MemoryStream();
        using var output = File.OpenWrite("test.png");
        await RenderWithSkia.ToPngStreamAsync(document, 1, output);
    }
}
```

then I get:

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/mark/dev/pdfrender/bin/Debug/net8.0/runtimes/linux-x64/native/kernel32.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.3/kernel32.dll.so: cannot open shared object file: No such file or directory
/home/mark/dev/pdfrender/bin/Debug/net8.0/kernel32.dll.so: cannot open shared object file: No such file or directory
/home/mark/dev/pdfrender/bin/Debug/net8.0/runtimes/linux-x64/native/libkernel32.dll.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.3/libkernel32.dll.so: cannot open shared object file: No such file or directory
/home/mark/dev/pdfrender/bin/Debug/net8.0/libkernel32.dll.so: cannot open shared object file: No such file or directory
/home/mark/dev/pdfrender/bin/Debug/net8.0/runtimes/linux-x64/native/kernel32.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.3/kernel32.dll: cannot open shared object file: No such file or directory
/home/mark/dev/pdfrender/bin/Debug/net8.0/kernel32.dll: cannot open shared object file: No such file or directory
/home/mark/dev/pdfrender/bin/Debug/net8.0/runtimes/linux-x64/native/libkernel32.dll: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.3/libkernel32.dll: cannot open shared object file: No such file or directory
/home/mark/dev/pdfrender/bin/Debug/net8.0/libkernel32.dll: cannot open shared object file: No such file or directory

   at Melville.SharpFont.ArchitectureDllImport.SetDllDirectory(String lpPathName)
   at Melville.SharpFont.ArchitectureDllImport.LoadArchitectureDependencyDirectory(String explicitFolder)
   at Melville.SharpFont.Library..ctor(String explicitForder)
   at Melville.Pdf.Model.Renderers.FontRenderings.FreeType.GlobalFreeTypeResources.LoadFontLibrary(String freetype6DllFolder)
   at Melville.Pdf.Model.Renderers.FontRenderings.FreeType.GlobalFreeTypeResources.get_SharpFontLibrary()
   at Melville.Pdf.Model.Renderers.FontRenderings.FreeType.FreeTypeFontFactory.FromCSharpStreamAsync(Stream source, Int32 index)
   at Melville.Pdf.Model.Renderers.FontRenderings.FreeType.FreeTypeFontFactory.FromStreamAsync(PdfStream pdfStream)
   at Melville.Pdf.Model.Renderers.FontRenderings.FreeType.FreeTypeFontFactory.FromStreamAsync(PdfStream pdfStream)
   at Melville.Pdf.Model.Renderers.FontRenderings.FontReader.CreateRealizedFontAsync(PdfFont fontStreamSource, FreeTypeFontFactory factory)
   at Melville.Pdf.Model.Renderers.RenderEngine.<CheckCacheForFontAsync>b__37_0(PdfDictionary r)
   at Melville.Pdf.Model.Renderers.DocumentPartCaches.DocumentPartCache.FindAndStoreValueAsync[T,TSource](TSource source, Func`2 creator)
   at Melville.Pdf.Model.Renderers.DocumentPartCaches.DocumentPartCache.GetAsync[TSource,T](TSource source, Func`2 creator)
   at Melville.Pdf.Model.Renderers.RenderEngine.FontFromDictionaryAsync(PdfDictionary fontDic)
   at Melville.Pdf.Model.Renderers.RenderEngine.SetFontAsync(PdfDirectObject font, Double size)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteTokenAsync(PostscriptValue token)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteTokenAsync(PostscriptValue token)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.MainExecutionLoopAsync()
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteAsync(ITokenSource tokens)
   at Melville.Pdf.LowLevel.Parsing.ContentStreams.ContentStreamParser.ParseAsync(PipeReader source)
   at Melville.Pdf.Model.Renderers.RenderEngine.RunContentStreamAsync()
   at Melville.Pdf.Model.Renderers.RenderEngine.RenderAsync(IHasPageAttributes xObject)
   at Melville.Pdf.Model.Renderers.RenderEngine.RunTargetGroupAsync(PdfStream xObjectAsStream)
   at Melville.Pdf.Model.Renderers.RenderEngine.DoAsync(PdfStream inlineImage)
   at Melville.Pdf.Model.Renderers.RenderEngine.DoAsync(PdfDirectObject name)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteTokenAsync(PostscriptValue token)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteTokenAsync(PostscriptValue token)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.MainExecutionLoopAsync()
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteAsync(ITokenSource tokens)
   at Melville.Pdf.LowLevel.Parsing.ContentStreams.ContentStreamParser.ParseAsync(PipeReader source)
   at Melville.Pdf.Model.Renderers.RenderEngine.RunContentStreamAsync()
   at Melville.Pdf.Model.Renderers.DocumentRenderers.DocumentRenderer.RenderPageToAsync(Int32 oneBasedPageNumber, Func`3 target)
   at Melville.Pdf.SkiaSharp.RenderWithSkia.ToSurfaceAsync(DocumentRenderer doc, Int32 oneBasedPageNumber, Int32 width, Int32 height)
   at Melville.Pdf.SkiaSharp.RenderWithSkia.ToPngStreamAsync(DocumentRenderer doc, Int32 oneBasedPageNumber, Stream target, Int32 width, Int32 height)
   at Test.Program.Main() in /home/mark/dev/pdfrender/Program.cs:line 15
   at Test.Program.<Main>()
```

**Comment by DrJohnMelville** [comment]
Thanks for the bug report.

I have never used linux for more than about 30 minutes at a time, so I will confess to some ignorance on this.  

the problem is in Melville.SharpFont.ArchitectureDllImport -- I explicitly use a Kernell32.dll function to tell windows where to look for the native dependency.  I obviously need a different solution for Linux.

My apologies, but I am not going to get to this in the next month or two.  If you choose to do a PR that doesn't break the windows support it would be greatly appreciated.

**Comment by DrJohnMelville** [comment]
This bug is obsolete becuase Melville.PDF no longer uses the native SharpFont library
