### ISSUE TITLE
Invalid Color space definition Exception

### ISSUE THREAD

**Issue by Matti-Koopa** [DrJohnMelville/Pdf#40]
(removed)

```
Melville.Pdf.LowLevel.Model.Primitives.PdfParseException: Invalid Color space definition
   at Melville.Pdf.Model.Renderers.Colors.ColorSpaceFactory.FromNameOrArrayAsync(PdfDirectObject datum)
   at Melville.Pdf.Model.Renderers.Colors.ColorSpaceFactory.LookupInResourceDictionaryAsync(PdfDirectObject colorSpaceName)
   at Melville.Pdf.Model.Renderers.ColorOperations.ColorMacroExpansions.SetNonstrokingColorSpaceAsync(PdfDirectObject colorSpace)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteTokenAsync(PostscriptValue token)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteTokenAsync(PostscriptValue token)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.RunSingleStepAsync(PostscriptValue token)
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.MainExecutionLoopAsync()
   at Melville.Postscript.Interpreter.InterpreterState.PostscriptEngine.ExecuteAsync(ITokenSource tokens)
   at Melville.Pdf.LowLevel.Parsing.ContentStreams.ContentStreamParser.ParseAsync(IByteSource source)
   at Melville.Pdf.Model.Renderers.RenderEngine.RunContentStreamAsync()
   at Melville.Pdf.Model.Renderers.DocumentRenderers.DocumentRenderer.RenderPageToAsync(Int32 oneBasedPageNumber, Func`3 target)
   at Melville.Pdf.TextExtractor.TextExtractorFacade.PageTextAsync(DocumentRenderer renderer, Int32 oneBasedPageNumber)
```

**Comment by DrJohnMelville** [comment]
Fixed in commit 73f21fd4
